### ISSUE TITLE
Allow work without wake_alarm capability

### ISSUE THREAD

**Issue by zvova7890** [waydroid/android_vendor_waydroid#19]
With  wake_alarm cap android is wakes up the host when it is suspended with waydroid running.

With attached patch android continue to work and not wakes up the host when no wake_alarm cap allowed.
Please consider to do something with this.
[work-without-wake_alarm-capability.patch.txt](https://github.com/waydroid/android_vendor_waydroid/files/10609979/work-without-wake_alarm-capability.patch.txt)

**Comment by electrikjesus** [comment]
Could you please update this PR to include the patch in the correct folder? I am assuming that the target is api-30, so your target folder is here: https://github.com/waydroid/android_vendor_waydroid/tree/lineage-18.1/waydroid-patches/base-patches-30/frameworks/base

You should just update your change to include git attribution also: $ git format-patch -1

**Comment by electrikjesus** [comment]
Closing this issue. Thanks for resubmitting
https://github.com/waydroid/android_vendor_waydroid/pull/20
